name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "needs triage"]
assignees: 
- octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out this form as completely as possible to help us address the issue.

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A clear and concise title for the bug.
      placeholder: "[BUG] Something isn't working"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please provide a detailed description of the bug.
      placeholder: "A detailed description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step description of how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen.
      placeholder: "What you expected to happen."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please describe what actually happened.
      placeholder: "What actually happened."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Versions Affected"
  # Dynamically generated versions list would go here
  - type: checkboxes
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Please select the version(s) affected.
      options:
        - label: Version 1.0
        - label: Version 1.1
        - label: Version 1.2
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Additional Context"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide any additional context, screenshots, or files that may help us understand the issue better.
      placeholder: "Any additional context."
    validations:
      required: false

  - type: file
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
