name: Psalm Static analysis

on:
  push:
     paths:
        - '**.php'
        - 'psalm.xml'
  pull_request:
     paths:
        - '**.php'
        - 'psalm.xml'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, xdebug
        env:
          update: true
      - name: Check PHP Version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate
        
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
           security_analysis: true
           report_file: results.sarif
           
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
           sarif_file: results.sarif
