name: Update Issue Template with Release Tags

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch the latest 5 release tags from another repository
        id: get-tags
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const tags = await github.rest.repos.listTags({
              owner: 'erusev',
              repo: 'parsedown',
              per_page: 5
            });
            return tags.data.map(tag => tag.name).join('\n');

      - name: Update issue template with tags
        run: |
          TEMPLATE_PATH=".github/ISSUE_TEMPLATE/bug_report.yaml"
          # The section in the YAML we plan to update
          YAML_SECTION_START='versions:'
          YAML_SECTION_END='# End of versions section'
          NEW_TAGS_SECTION="${{ steps.get-tags.outputs.result }}"
          
          # Extract everything before and after the tags section
          before_tags=$(awk "/${YAML_SECTION_START}/{exit} {print}" $TEMPLATE_PATH)
          after_tags=$(awk "/${YAML_SECTION_END}/,0" $TEMPLATE_PATH)
          
          # Reconstruct the file
          echo "$before_tags" > $TEMPLATE_PATH
          echo "$YAML_SECTION_START" >> $TEMPLATE_PATH
          IFS=$'\n'
          for TAG in $NEW_TAGS_SECTION; do
            echo "  - $TAG" >> $TEMPLATE_PATH
          done
          echo "$after_tags" >> $TEMPLATE_PATH

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $TEMPLATE_PATH
          git diff --staged --quiet || git commit -m "Update issue template with latest release tags"
          git push
